---
version: "2"
checks:
  similar-code:
    enabled: false
plugins:
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
exclude_patterns:
- .idea/
- node_modules/
- test/
