language: node_js
node_js:
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - '13'
  - node
  - lts/*
script:
  - npm run lint
  - npm test
notifications:
  emails: false
  slack:
    secure: 2El+urL4uCbXVyX6A5Gk4sZbWLSt7n02VckuUD+E5a0mwr05M0lP5RRRfEisOe0q1hsprOXXpcdb8gf7r2AHdVD4iVJGV9GAHtmOqn5qFy1URCOl/Q/OtkuGLEjoLU9nRp0v4b+hZ2RHvNLX1lYF1QGcN2omS7yAKZMRNCPmb9SggEYSkmQo+q6C26TtZKda2gBK+CIZP96hsEaJIsjJGLIHaRG+v+NjH43B3grHf20IpblTMNAiXoD9lDJjngTwrxqNkUjPNcRGDqAY+D2Mdk7bB3CqcU6rsGtekXTRoYwBYz1GJ5dlcyI2QdXxYLoo6rLy/Q1f4QfQd51cYqULoWFlk9SJ45HnhgNxotskrNiq4S9bgqKTIDkLYeDFg2ZOcRqeeAj7mHtqc8+r82oDfvGn6l/vLU4eBfwIhWg/YN7IZHMVDUuIelmqGQBhTlmBJ00uaI5R4K6Oze/RtbJ2e8SDOBH6BMq21p/w7qdCTc1Tlpb8akX5DAvWR4e+c7kf80vV2Kq9A3+DtdMGmcO93Bwvdrrrmkoq9ROUybDl4HcSW+9wDdfNA/fZAXLT7HpLwwVIVlc4HelokKQkbSuqdg/ls9yprd85QcVjlGY8iyTsQrgrCABK2i14G3VY61S8G6vX6pHGWZtkqlXwISFhSLVeBIcTIMogIJOoqAFEpqs=
