name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      - name: Install ts-jest explicitly
        run: npm install ts-jest@29.1.1 jest@29.7.0 @types/jest typescript
        
      - name: Run tests with Jest
        run: NODE_OPTIONS=--experimental-vm-modules npx ts-jest config:migrate jest.config.cjs && NODE_OPTIONS=--experimental-vm-modules npx jest --config=jest.config.cjs
